version: '3.8'
services:
  webserver:
    build: ./docker/webserver
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '.:/var/www/html'
  mysql:
    image: mariadb
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: spadajace_kwadraciki
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345678
  node:
    build: ./docker/node
    volumes:
      - '.:/files'
